BilheticaAeronauticaWeb/Entities/ShoppingBasketTicket.cs
using System.ComponentModel.DataAnnotations;
using NuGet.ContentModel;

namespace BilheticaAeronauticaWeb.Entities
{
    public class ShoppingBasketTicket : IEntity
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Surname { get; set; }

        //[Required]
        //public int OriginAirportId { get; set; }

        //[Required]
        //public int DestinationAirportId { get; set; }

        public int? SeatId { get; set; }

        public Seat? Seat { get; set; }

        [Required]
        public Flight Flight { get; set; }


        public int FlightId { get; set; }

        [Required]
        public PassengerType PassengerType { get; set; }

        [Required]
        public TicketClass Class { get; set; }

        [Required]
        public decimal Price { get; set; }

        public int? ResponsibleAdultTicketId { get; set; }

        public bool IsResponsibleAdult { get; set; }

        public string? UserId { get; set; }

        public User? User { get; set; }


    }
}

BilheticaAeronauticaWeb/Models/ShoppingBasketTicketViewModel.cs
using BilheticaAeronauticaWeb.Entities;
using System.ComponentModel;

namespace BilheticaAeronauticaWeb.Models
{
    public class ShoppingBasketTicketViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Surname { get; set; }

        public int? SeatId { get; set; }

        public int FlightId { get; set; }

        public Flight Flight { get; set; }

        [DisplayName("Passenger type")]
        public PassengerType PassengerType { get; set; }

        public TicketClass Class { get; set; }

        public decimal Price { get; set; }

        public int? ResponsibleAdultTicketId { get; set; }

        public string? UserId { get; set; }
    }
}

BilheticaAeronauticaWeb/Controllers/ShoppingBasketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BilheticaAeronauticaWeb.Data;
using BilheticaAeronauticaWeb.Entities;
using BilheticaAeronauticaWeb.Helpers;
using BilheticaAeronauticaWeb.Models;
using BilheticaAeronauticaWeb.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BilheticaAeronauticaWeb.Controllers
{
    public class ShoppingBasketsController : Controller
    {
        private readonly IUserHelper _userHelper;
        private readonly IConverterHelper _converterHelper;
        private readonly IShoppingBasketRepository _shoppingBasketRepository;
        private readonly ITicketRepository _ticketRepository;
        private readonly IBasketHelper _basketHelper;
        private readonly ITicketService _ticketService;
        private readonly IFlightRepository _flightRepository;
        private readonly ISeatRepository _seatRepository;

        public ShoppingBasketsController(IUserHelper userHelper,
            IConverterHelper converterHelper,
            IShoppingBasketRepository shoppingBasketRepository,
            ITicketRepository ticketRepository,
            IBasketHelper basketHelper,
            ITicketService ticketService,
            IFlightRepository flightRepository,
            ISeatRepository seatRepository)
        {
            _userHelper = userHelper;
            _converterHelper = converterHelper;
            _shoppingBasketRepository = shoppingBasketRepository;
            _ticketRepository = ticketRepository;
            _basketHelper = basketHelper;
            _ticketService = ticketService;
            _flightRepository = flightRepository;
            _seatRepository = seatRepository;
        }

        // GET: ShoppingBaskets
        public async Task<IActionResult> Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = await _userHelper.GetUserByEmailAsync(User.Identity.Name);

                if (user != null)
                {
                    var shoppingBasketTicketsWithUser = await GetRegisteredUserBasketTickets(user);

                    return View("Views/ShoppingBaskets/Index.cshtml", shoppingBasketTicketsWithUser);
                }
            }

            var shoppingBasketTicketsWithoutUser = await GetUnegisteredUserBasketTickets();

            return View("Views/ShoppingBaskets/Index.cshtml", shoppingBasketTicketsWithoutUser);
        }



        ////GET: ShoppingBaskets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("TicketNotFound");
            }

            ShoppingBasketTicket shoppingBasketTicket = await _shoppingBasketRepository.GetShoppingBasketTicketAsync(id.Value);

            if (shoppingBasketTicket == null)
            {
                return new NotFoundViewResult("TicketNotFound");
            }

            return View(shoppingBasketTicket);
        }

        // GET: ShoppingBaskets/Create
        public IActionResult Create()
        {
            return View();
        }

        //// POST: ShoppingBaskets/Create
        //// To protect from overposting attacks, enable the specific properties you want to bind to.
        //// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateShoppingBasketTicket(TicketViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Type == PassengerType.Infant && model.ResponsibleAdultTicketId == null)
                {
                    ViewBag.Adults = await GetAdultsFromBasket(model);

                    if (ViewBag.Adults.Count == 0)
                    {
                        return View("AddAdults");
                    }
                    else
                    {
                        return View("ChooseResponsibleForInfant", model);
                    }
                }
                else if(model.Type == PassengerType.Infant && model.ResponsibleAdultTicketId != null)
                {
                    await AssignResponsibleAdult(model);
                }
                
                if (model.FlightId != null)
                {
                        var basketTicket = _converterHelper.ToShoppingBasketTicket(model, true);

                        if (User.Identity.IsAuthenticated)
                        {
                            var user = await _userHelper.GetUserByEmailAsync(User.Identity.Name);

                            if (user != null)
                            {
                                await AddBasketTicketWithUser(user, basketTicket);
                            }
                        }
                        else
                        {
                            await AddBasketTicketWithoutUser(basketTicket);
                        }

                        if (basketTicket.SeatId != null)
                        {
                            await _ticketService.HoldSeat(basketTicket.SeatId.Value);
                        }

                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Index");
        }



        // POST: ShoppingBaskets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Purchase()
        {
            var shoppingBasketTickets = new List<ShoppingBasketTicket>();
            User? user = null;

            if (User.Identity.IsAuthenticated)
            {
                user = await _userHelper.GetUserByEmailAsync(User.Identity.Name);
                shoppingBasketTickets = await _shoppingBasketRepository.GetShoppingBasketTicketsAsync(user);
            }
            else
            {
                shoppingBasketTickets = _basketHelper.GetBasketTickets(HttpContext.Session);

                foreach (var ticket in shoppingBasketTickets)
                {
                    ticket.Flight = await _flightRepository.GetByIdAsync(ticket.FlightId);
                }
            }

            if (!shoppingBasketTickets.Any())
            {
                return View("NoShoppingBasket");
            }

            var shoppingBasketWithUserViewModel = ConvertToTicketWithUserViewModel(shoppingBasketTickets, user);

            ViewBag.Seats = await GetSeatsViewBag(shoppingBasketWithUserViewModel);

            return View(shoppingBasketWithUserViewModel);

        }

        // GET: ShoppingBasket/Delete/5
        //[Authorize(Roles = "Customer")]
        public async Task<IActionResult> Delete(int? id)
        {
            User? user = null;

            if (id == null)
            {
                return new NotFoundViewResult("TicketNotFound");
            }

            var ticket = await _shoppingBasketRepository.GetShoppingBasketTicketAsync(id.Value);


            if (ticket == null)
            {
                return new NotFoundViewResult("TicketNotFound");
            }

            return View(ticket);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ticket = await _shoppingBasketRepository.GetShoppingBasketTicketAsync(id);

            try
            {
                await _shoppingBasketRepository.DeleteAsync(ticket);

                if (!User.Identity.IsAuthenticated)
                {
                    var basket = _basketHelper.GetBasketTickets(HttpContext.Session);
                    var localTickt = basket.FirstOrDefault(t => t.Id == id);

                    if (localTickt != null)
                    {
                        basket.Remove(localTickt);
                        _basketHelper.SaveBasketTickets(HttpContext.Session, basket);
                    }
                }

                if (ticket.Seat != null)
                {
                    await _ticketService.UnholdSeat(ticket.Seat);
                }

                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException ex)
            {

                if (ex.InnerException != null && ex.InnerException.Message.Contains("DELETE"))
                {
                    var errorModel = new ErrorViewModel
                    {
                        ErrorTitle = $"{ticket.Id} provavelmente está a ser usado!!",
                        ErrorMessage = $"{ticket.Id} não pode ser apagado.<br/><br/>" 
                    };

                    return View("Error", errorModel);
                }


                return View("Error", new ErrorViewModel
                {
                    ErrorTitle = "Erro de base de dados",
                    ErrorMessage = "Ocorreu um erro inesperado ao tentar apagar o ticket."
                });

            }
        }

        [HttpPost]
        [Route("ShoppingBaskets/GetAdultsFromBasket")]
        public async Task<List<SelectListItem>> GetAdultsFromBasket(TicketViewModel model)
        {
            var shoppingBasketTickets = new List<ShoppingBasketTicket>();

            if (User.Identity.IsAuthenticated)
            {
                var user = await _userHelper.GetUserByEmailAsync(User.Identity.Name);

                if (user != null)
                {
                    shoppingBasketTickets = await _shoppingBasketRepository.GetShoppingBasketTicketsAsync(user);
                }
            }
            else
            {

BilheticaAeronauticaWeb/Views/ShoppingBaskets/AddAdults.cshtml
@{
    <br />
    <div class="row justify-content-center">
        <div class="col-md-6 text-center">
            <h3>Please add an adult ticket first</h3>
        </div>
    </div>
}

BilheticaAeronauticaWeb/Views/ShoppingBaskets/ChooseResponsibleForInfant.cshtml
@using BilheticaAeronauticaWeb.Entities
@model BilheticaAeronauticaWeb.Models.TicketViewModel

@{
    ViewData["Title"] = "Details";
}


<div>
    <br />
     <form asp-controller="ShoppingBaskets" asp-action="CreateShoppingBasketTicket" method="post">
    <dl class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Name" type="hidden" />
            <input asp-for="Surname" type="hidden" />
            <input asp-for="FlightId" type="hidden" />
            <input asp-for="Class" type="hidden" />
            <input asp-for="OriginAirportId" type="hidden" />
            <input asp-for="DestinationAirportId" type="hidden" />
            <input asp-for="Price" type="hidden" />
            <input asp-for="Type" type="hidden" />

            <div class="d-flex align-items-center">
                <select id="ResponsibleAdultTicketId" name="ResponsibleAdultTicketId" class="form-control" asp-items="ViewBag.Adults">
                    <option value="">Select a responsible adult</option>
                </select>

                <input type="submit" value="Confirm" class="btn btn-info ms-3 me-2" />
                <a asp-action="Index" class="btn btn-danger btn-dark" me-2">Back</a>
            </div>
    </dl>
    </form>
</div>

BilheticaAeronauticaWeb/Views/ShoppingBaskets/Delete.cshtml
@model BilheticaAeronauticaWeb.Entities.ShoppingBasketTicket

@{
    ViewData["Title"] = "Delete";
}


<br />
<div class="row justify-content-center">

<div class="col-md-6">
        <h3>Are you sure you want to delete this?</h3>
        <hr />

    <p><strong>@Html.DisplayNameFor(model => model.Name):</strong> @Html.DisplayFor(model => model.Name)</p>
    <p><strong>@Html.DisplayNameFor(model => model.Surname):</strong> @Html.DisplayFor(model => model.Surname)</p>
    <p>
        <strong>@Html.DisplayNameFor(model => model.Flight):</strong>
        @Html.DisplayFor(model => model.Flight.OriginAirport.Name) to @Html.DisplayFor(model => model.Flight.DestinationAirport.Name)
    </p>
    <p><strong>@Html.DisplayNameFor(model => model.Class):</strong> @Html.DisplayFor(model => model.Class)</p>
        @if (Model.Seat != null)
        {
            <p><strong>@Html.DisplayNameFor(model => model.Seat.Row):</strong> @Html.DisplayFor(model => model.Seat.Row)</p>
            <p><strong>@Html.DisplayNameFor(model => model.Seat.Column):</strong> @Html.DisplayFor(model => model.Seat.Column)</p>
        }
        else
        {
            <p><strong>Seat:</strong> Not assigned</p>
        }
    <p><strong>@Html.DisplayNameFor(model => model.Price):</strong> @Html.DisplayFor(model => model.Price)</p>
        <p><strong>Passenger Type:</strong> @Html.DisplayFor(model => model.PassengerType)</p>

    <div class="mt-4">
            <form asp-action="Delete" asp-route-id="@Model?.Id" method="post" class="d-inline">
                <button type="submit" class="btn btn-danger btn-dark me-2">Delete</button>
            </form>
        <a asp-action="Index" class="btn btn-secondary">Back</a>
    </div>

</div>

BilheticaAeronauticaWeb/Views/ShoppingBaskets/Details.cshtml
@model BilheticaAeronauticaWeb.Entities.ShoppingBasketTicket

@{
    ViewData["Title"] = "Details";
}

<br />
<h1 class="text-center">Ticket Info</h1>
<hr />
<div class="row justify-content-center">
    <div class="col-md-6">

        <p><strong>@Html.DisplayNameFor(model => model.Name):</strong> @Html.DisplayFor(model => model.Name)</p>
        <p><strong>@Html.DisplayNameFor(model => model.Surname):</strong> @Html.DisplayFor(model => model.Surname)</p>
        <p>
            <strong>@Html.DisplayNameFor(model => model.Flight):</strong>
            @Html.DisplayFor(model => model.Flight.OriginAirport.Name) to @Html.DisplayFor(model => model.Flight.DestinationAirport.Name)
        </p>
        <p><strong>@Html.DisplayNameFor(model => model.Class):</strong> @Html.DisplayFor(model => model.Class)</p>

        @if (Model.Seat != null)
        {
            <p><strong>@Html.DisplayNameFor(model => model.Seat.Row):</strong> @Html.DisplayFor(model => model.Seat.Row)</p>
            <p><strong>@Html.DisplayNameFor(model => model.Seat.Column):</strong> @Html.DisplayFor(model => model.Seat.Column)</p>
        }
        else
        {
            <p><strong>Seat:</strong> Not assigned</p>
        }

        <p><strong>@Html.DisplayNameFor(model => model.Price):</strong> @Html.DisplayFor(model => model.Price)</p>

        <p><strong>Passenger Type:</strong> @Html.DisplayFor(model => model.PassengerType)</p>

        <div class="mt-4">
            <a asp-action="Index" class="btn btn-secondary">Back</a>
        </div>

    </div>
</div>

BilheticaAeronauticaWeb/Views/ShoppingBaskets/Edit.cshtml
@* @model BilheticaAeronauticaWeb.Entities.ShoppingBasket

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ShoppingBasket</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

 *@

BilheticaAeronauticaWeb/Views/ShoppingBaskets/Index.cshtml
@model BilheticaAeronauticaWeb.Models.ShoppingBasketWithUserViewModel

@{
    ViewData["Title"] = "Index";

}
<br />
<h1>Your Shopping Basket</h1>
<br />
<br />

@if (Model.ShoppingBasketTickets.Any()){
    <div class="card-body">
</div>


<div class="card mb-4">
    <div class="card-header">
    </div>
    <div class="card-body">
        <table id="datatablesSimple" class="table table-bordered">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Surname</th>
                    <th>Class</th>
                    <th>Origin</th>
                    <th>Destination</th>
                    <th>Layover</th>
                    <th>Price</th>
                    <th>Type</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.ShoppingBasketTickets)
                {
                    <tr>
                        <td>@item.Name</td>
                        <td>@item.Surname</td>
                        <td>@item.Class</td>
                        <td>@item.Flight.OriginAirport.Name</td>
                        <td>@item.Flight.DestinationAirport.Name</td>
                            @if (item.Flight.Layover != null)
                            {
                                <td>@item.Flight.Layover.Name</td>
                            }
                            else
                            {
                                <td>N/A</td>
                            }
                            <td>@item.Price.ToString("C")</td>
                        <td>@item.PassengerType</td>
                        <td>
                                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info">Info</a>
                                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-dark">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>


<form asp-action="Purchase" method="post">  <button type="submit" class="btn btn-success">Purchase</button>
</form>
}

BilheticaAeronauticaWeb/Views/ShoppingBaskets/NoShoppingBasket.cshtml
@{
    ViewData["Title"] = "No Shopping Basket";
}

<h2>Shopping Basket empty</h2>

<p>To add tickets to your shopping basket, please select a flight first.</p>

BilheticaAeronauticaWeb/Views/ShoppingBaskets/Purchase.cshtml
@model BilheticaAeronauticaWeb.Models.ShoppingBasketWithUserViewModel

@{
    ViewData["Title"] = "Purchase";
}

<br />
<h1>Your Final Order</h1>
<br />
<form asp-controller="Orders" asp-action="Purchase" method="post">
    <div asp-validation-summary="ModelOnly"></div>

    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Surname</th>
                <th>Class</th>
                <th>Passenger type</th>
                <th>Origin</th>
                <th>Destination</th>
                <th>Layover</th>
                <th>Price</th>
                <th>Seat</th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.ShoppingBasketTickets.Count; i++)
            {
                var item = Model.ShoppingBasketTickets[i];
                <tr>
                    <td>
                        <input type="hidden" asp-for="ShoppingBasketTickets[@i].Name" />
                        @item.Name
                    </td>
                    <td>
                        <input type="hidden" asp-for="ShoppingBasketTickets[@i].Surname" />
                        @item.Surname
                    </td>
                    <td>
                        <input type="hidden" asp-for="ShoppingBasketTickets[@i].Class" />
                        @item.Class
                    </td>
                    <td>
                        <input type="hidden" asp-for="ShoppingBasketTickets[@i].PassengerType" />
                        @item.PassengerType
                    </td>
                    <td>
                        <input type="hidden" asp-for="ShoppingBasketTickets[@i].Flight.OriginAirport.Name" />
                        @item.Flight.OriginAirport.Name
                    </td>
                    <td>
                        <input type="hidden" asp-for="ShoppingBasketTickets[@i].Flight.DestinationAirport.Name" />
                        @item.Flight.DestinationAirport.Name
                    </td>
                    <td>
                        @if (item.Flight.Layover != null)
                        {
                            <input type="hidden" asp-for="ShoppingBasketTickets[@i].Flight.Layover.Name" />
                            @item.Flight.Layover.Name
                        }
                        else
                        {
                            <p>N/A</p>
                        }

                    </td>

                        <input type="hidden" asp-for="ShoppingBasketTickets[@i].FlightId" />

                    <td>
                        <input type="hidden" asp-for="ShoppingBasketTickets[@i].Price" />
                        @item.Price.ToString("C")
                    </td>
                    <td>
                        @if (item.SeatId == null || item.SeatId == 0)
                        {
                            <span class="text-danger">Please choose a seat</span>
                            <select asp-for="ShoppingBasketTickets[@i].SeatId"
                                    class="form-control seat-dropdown"
                                    data-index="@i">
                                <option value="">Select a seat</option>
                                @{
                                    var seatsList = ViewBag.Seats as IEnumerable<SelectListItem>;
                                }
                                @foreach (var seat in seatsList)
                                {
                                    <option value="@seat.Value">@seat.Text</option>
                                }
                            </select>
                        }
                        else
                        {
                            @item.SeatId
                            <input type="hidden" asp-for="ShoppingBasketTickets[@i].SeatId" />
                        }
                    </td>
                </tr>
            }

        </tbody>
    </table>
    <br />
    @if (!User.Identity.IsAuthenticated)
    {
        <div class="form-group">
            <label asp-for="NewUser.FirstName">First Name</label>
            <input asp-for="NewUser.FirstName" class="form-control" />
            <span asp-validation-for="NewUser.FirstName" class="text-warning"></span>
        </div>

        <div class="form-group">
            <label asp-for="NewUser.LastName">Last Name</label>
            <input asp-for="NewUser.LastName" class="form-control" />
            <span asp-validation-for="NewUser.LastName" class="text-warning"></span>
        </div>

        <div class="form-group">
            <label asp-for="NewUser.Username">Username</label>
            <input asp-for="NewUser.Username" class="form-control" />
            <span asp-validation-for="NewUser.Username" class="text-warning"></span>
        </div>

        <div class="form-group">
            <label asp-for="NewUser.Password">Password</label>
            <input asp-for="NewUser.Password" type="password" class="form-control" />
            <span asp-validation-for="NewUser.Password" class="text-warning"></span>
        </div>

        <div class="form-group">
            <label asp-for="NewUser.Confirm">Confirm Password</label>
            <input asp-for="NewUser.Confirm" type="password" class="form-control" />
            <span asp-validation-for="NewUser.Confirm" class="text-warning"></span>
        </div>
    }

    <div class="text-center mt-3">
        <button type="submit" class="btn btn-success">Confirm</button>
    </div>
</form>


@section Scripts {
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const seatDropdowns = document.querySelectorAll('.seat-dropdown');
            const allSeatOptions = {};

            // Save the original options
            seatDropdowns.forEach(dropdown => {
                const index = dropdown.dataset.index;
                allSeatOptions[index] = Array.from(dropdown.options).map(option => option.cloneNode(true));
            });

            seatDropdowns.forEach(dropdown => {
                dropdown.addEventListener('change', function () {
                    const selectedSeat = this.value;

                    // Rebuild all dropdowns
                    seatDropdowns.forEach(innerDropdown => {
                        const innerIndex = innerDropdown.dataset.index;

                        const currentValue = innerDropdown.value;

                        // Clear all options
                        innerDropdown.innerHTML = '';

                        // Restore from original list
                        allSeatOptions[innerIndex].forEach(option => {
                            if (
                                option.value === '' ||                    // keep placeholder
                                option.value === currentValue ||          // keep its own selection
                                option.value !== selectedSeat             // exclude seat selected by someone else
                            ) {
                                innerDropdown.appendChild(option.cloneNode(true));
                            }
                        });

                        // Re-apply the user's selection
                        innerDropdown.value = currentValue;
                    });
                });
            });
        });
    </script>
}

BilheticaAeronauticaWeb/Views/ShoppingBaskets/ShoppingBasketTickets.cshtml
@model BilheticaAeronauticaWeb.Models.ShoppingBasketWithUserViewModel

@{
    ViewData["Title"] = "ShoppingBasketTickets";
}

<h1>Your Shopping Basket</h1>

<p>
    <a asp-action="AddTicket" class="btn btn-primary">Add more tickets</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Surname</th>
            <th>Class</th>
            <th>Flight</th>
            <th>Price</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ShoppingBasketTickets)
        {
            <tr>
                <td>@item.Name</td>
                <td>@item.Surname</td>
                <td>@item.Class</td>
                <td>@item.FlightId</td>
                <td>@item.Price.ToString("C")</td>
                <td>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<p>
    <a asp-action="Purchase" class="btn btn-success">Purchase</a>
</p>