BilheticaAeronauticaWeb/Entities/Airport.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace BilheticaAeronauticaWeb.Entities
{
    public class Airport : IEntity
    {
        public int Id { get; set; }

        [Required] 
        [MaxLength(100, ErrorMessage = "The field {0} cannot contain more than {1} characters length.")]
        public string Name { get; set; }

        public int CityId { get; set; }
        public City City { get; set; }

        public int CountryId { get; set; }
        public Country Country { get; set; }

        
    }
}

BilheticaAeronauticaWeb/Models/AirportViewModel.cs
using System.ComponentModel.DataAnnotations;
using BilheticaAeronauticaWeb.Entities;

namespace BilheticaAeronauticaWeb.Models
{
    public class AirportViewModel
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required(ErrorMessage = "Country is required.")]
        public int CountryId { get; set; }

        [Required(ErrorMessage = "City is required.")]
        [Range(1, int.MaxValue, ErrorMessage = "Please select a valid city.")]
        public int CityId { get; set; }
    }
}

BilheticaAeronauticaWeb/Controllers/API/AirportsController.cs
using BilheticaAeronauticaWeb.Data;
using Microsoft.AspNetCore.Mvc;

namespace BilheticaAeronauticaWeb.Controllers.API
{
    [Route("api/[controller]")]
    [ApiController]
    public class AirportsController : Controller
    {
        private readonly IAirportRepository _airportRepository;


        public AirportsController(IAirportRepository airportRepository)
        {
            _airportRepository = airportRepository;
        }

        [HttpGet("GetAllAirports")]
        public IActionResult GetAllAirports()
        {
            var airports = _airportRepository.GetAll();

            return Ok(airports);
        }
    }
}

BilheticaAeronauticaWeb/Controllers/AirportsController.cs
using System.Diagnostics;
using System.Runtime.InteropServices;
using BilheticaAeronauticaWeb.Data;
using BilheticaAeronauticaWeb.Entities;
using BilheticaAeronauticaWeb.Helpers;
using BilheticaAeronauticaWeb.Models;
using BilheticaAeronauticaWeb.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Syncfusion.EJ2;
using Vereyon.Web;

namespace BilheticaAeronauticaWeb.Controllers
{
    [Authorize]
    public class AirportsController : Controller
    {
        private readonly IAirportRepository _airportRepository;
        private readonly ICountryRepository _countryRepository;
        private readonly IConverterHelper _converterHelper;
        private readonly IAirportService _airportService;
        private readonly IFlashMessage _flashMessage;

        public AirportsController(IAirportRepository aeroportoRepository,
            IConverterHelper converterHelper,
            ICountryRepository countryRepository,
            IAirportService airportService,
            IFlashMessage flashMessage)
        {
            _airportRepository = aeroportoRepository;
            _converterHelper = converterHelper;
            _countryRepository = countryRepository;
            _airportService = airportService;
            _flashMessage = flashMessage;
        }

        // GET: Airports
        public async Task<IActionResult> Index()
        {
            ViewBag.countryData = await _airportRepository.GetAirportCountriesForMapAsync();

            ViewBag.worldmap = GetWorldMap();

            var airports = _airportRepository.GetAll().OrderBy(a => a.Name).ToList();

            return View(airports);
        }

        // GET: Airports/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("AirportNotFound");
            }

            var airport = await _airportRepository.GetByIdAsync(id.Value);


            if (airport == null)
            {
                return new NotFoundViewResult("AirportNotFound");
            }

            return View(airport);
        }

        // GET: Airports/Create
        public IActionResult Create()
        {
            ViewBag.Countries = _countryRepository.GetComboCountries(true);

            ViewBag.Cities = new List<SelectListItem>
            {
                new SelectListItem { Text = "(Select a country first...)", Value = "0" }
            };

            return View();
        }

        // POST: Airports/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AirportViewModel model)
        {
            if (ModelState.IsValid)
            {
                var airport = await _converterHelper.ToAirport(model, true);

                try
                {
                    await _airportRepository.CreateAsync(airport);
                    _flashMessage.Info("Airplane created successfully!");
                    return RedirectToAction(nameof(Index));

                }
                catch (Exception ex)
                {
                    _flashMessage.Danger("This airport already exists!");
                }
            }
            return View(model);
        }

        // GET: Airports/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("AirportNotFound");
            }

            var airport = await _airportRepository.GetByIdAsync(id.Value);

            if (airport == null)
            {
                return new NotFoundViewResult("AirportNotFound");
            }

            var model = _converterHelper.ToAirportViewModel(airport);

            ViewBag.Countries = _countryRepository.GetComboCountries(false);

            ViewBag.Cities = new List<SelectListItem>
            {
                new SelectListItem { Text = "(Select a country first...)", Value = "0" }
            };

            return View(model);

        }

        // POST: Airports/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(AirportViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var airport = await _converterHelper.ToAirport(model, false);

                    var canEdit = await _airportService.AllowAirportDeletionOrUpdate(airport);

                    if (canEdit)
                    {
                        await _airportRepository.UpdateAsync(airport);
                        _flashMessage.Info("Airport edited successfully");
                    }
                    else
                    {
                        _flashMessage.Danger("This airport cannot be edited");
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await _airportRepository.ExistAsync(model.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        _flashMessage.Danger("This airport failed to be edited"); ;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [HttpPost]
        [Route("Airports/GetCitiesAsync")]
        public async Task<JsonResult> GetCitiesAsync(int countryId)
        {
            if (countryId > 0) 
            {
                var country = await _countryRepository.GetCountryWithCitiesAsync(countryId);
                return Json(country.Cities.OrderBy(c => c.Name));
            }

            return Json(Enumerable.Empty<City>());
        }

        // GET: Aeroportos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("AirportNotFound");
            }

            var airport = await _airportRepository.GetByIdAsync(id.Value);

            if (airport == null)
            {
                return new NotFoundViewResult("AirportNotFound");
            }

            return View(airport);
        }

        // POST: Aeroportos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var airport = await _airportRepository.GetByIdAsync(id);

            try
            {
                var canDelete = await _airportService.AllowAirportDeletionOrUpdate(airport);

                if (canDelete)
                {
                    await _airportRepository.DeleteAsync(airport);
                    _flashMessage.Info("Airport deleted successfully");
                }
                else
                {
                    _flashMessage.Danger("This airport cannot be deleted");
                }

                    return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException ex)
            {
                
                if (ex.InnerException != null && ex.InnerException.Message.Contains("DELETE"))
                {
                    var errorModel = new ErrorViewModel
                    {
                        ErrorTitle = $"{airport.Name} provavelmente está a ser usado!!",
                        ErrorMessage = $"{airport.Name} não pode ser apagado visto haverem encomendas que o usam.<br/><br/>" +
                                      $"Experimente primeiro apagar todas as encomendas que o estão a usar," +
                                      $"e torne novamente a apagá-lo"
                    };

                    return View("Error", errorModel);
                }

                
                return View("Error", new ErrorViewModel
                {
                    ErrorTitle = "Erro de base de dados",
                    ErrorMessage = "Ocorreu um erro inesperado ao tentar apagar o aeroporto."
                });

            }
        }

        public IActionResult AirportNotFound()
        {
            return View();
        }

        public object GetWorldMap()
        {
            string allText = System.IO.File.ReadAllText("./wwwroot/maps/worldmap.json");
            return JsonConvert.DeserializeObject(allText);
        }

    }
}

BilheticaAeronauticaWeb/Views/Airports/AirportNotFound.cshtml
@{
    ViewData["Title"] = "Airport Not Found";
}

<h2>Airport not found</h2>

BilheticaAeronauticaWeb/Views/Airports/Create.cshtml
@model BilheticaAeronauticaWeb.Models.AirportViewModel

@{
    ViewData["Title"] = "Create";
}
</br>
<h1>Add airport</h1>


<hr />
<div class="row">
    <div class="row justify-content-center">
        <div class="col-md-4 text-center">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
                <div class="form-group d-flex align-items-center">
                    <div class="flex-grow-1 me-2">
                        <label asp-for="CountryId" class="control-label">Country</label>
                        <select asp-for="CountryId" id="CountryId" asp-items="ViewBag.Countries" class="form-control">
                            <option value="">Select a country</option>
                        </select>
                        <span asp-validation-for="CountryId" class="text-danger"></span>
                    </div>
                    <div>
                        <a asp-action="Create" asp-controller="Countries" class="btn btn-warning btn-light mt-4">Add</a>
                    </div>
                </div>

                <div class="form-group d-flex align-items-center">
                    <div class="flex-grow-1 me-2">
                        <label asp-for="CityId" class="control-label">City</label>
                        <select asp-for="CityId" id="CityId" asp-items="ViewBag.Cities" class="form-control">
                            <option value="">Select a city</option>
                        </select>
                        <span asp-validation-for="CityId" class="text-danger"></span>
                    </div>
                    <div>
                        <a href="#" class="btn btn-warning btn-light mt-4" id="addCityBtn">Add</a>
                    </div>
                </div>
                <div class="form-group justify-content-center">
                    <input type="submit" value="Create" class="btn btn-info me-2" />
                </div>

        </form>
        </div>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }


    <script type="text/javascript">
        $(document).ready(function () {
            $("#CountryId").change(function () {
                $("#CityId").empty();
                $.ajax({
                    url: '@Url.Action("GetCitiesAsync", "Airports")',
                    type: 'POST',
                    dataType: 'json',
                    data: {countryId:$("#CountryId").val()},
                    success: function (cities) {
                        debugger;
                        $("#CityId").append('<option value="0">(Select a city...)</option>');
                        $.each(cities, function (i, city) {
                            $("#CityId").append('<option value="'
                                + city.id + '">'
                                + city.name + '</option>');
                        });
                    },
                    error: function (ex) {
                        debugger;
                        alert('Failed to retrieve cities.' + ex);
                    }
                });
                return false;
            })
        });
    </script>

    <script>
        document.getElementById("addCityBtn").addEventListener("click", function (e) {
            const countryId = document.getElementById("CountryId").value;

            if (!countryId) {
                alert("Please select a country first.");
                e.preventDefault();
                return;
            }

            window.location.href = `/Countries/AddCity?countryId=${countryId}`;
        });
    </script>

        }

BilheticaAeronauticaWeb/Views/Airports/Delete.cshtml
@model BilheticaAeronauticaWeb.Entities.Airport

@{
    ViewData["Title"] = "Delete";
}
<br />
<h3 class="text-center mb-4">Are you sure you want to delete this airport?</h3>
<hr />
<div class="row justify-content-center">
    <div class="col-md-6">
        <p><strong>@Html.DisplayNameFor(model => model.Name):</strong> @Html.DisplayFor(model => model.Name)</p>
        <p><strong>@Html.DisplayNameFor(model => model.City):</strong> @Html.DisplayFor(model => model.City.Name)</p>
        <p><strong>@Html.DisplayNameFor(model => model.Country):</strong> @Html.DisplayFor(model => model.Country.Name)</p>
    </div>
</div>


    <div class="text-center mt-4">
        <form asp-action="Delete" class="d-inline">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Delete" class="btn btn-danger me-2" />
        </form>
        <a asp-action="Index" class="btn btn-secondary">Back</a>
    </div>
</div>

BilheticaAeronauticaWeb/Views/Airports/Details.cshtml
@model BilheticaAeronauticaWeb.Entities.Airport

@{
    ViewData["Title"] = "Details";
}
</br>
<h1>Details</h1>

<div class="row justify-content-center"> 
    <div class="col-md-4">
        <dl class="row">
            <dt class="col-sm-4 text-end">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-4 text-end">
                @Html.DisplayNameFor(model => model.City.Name)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.City.Name)
            </dd>
            <dt class="col-sm-4 text-end">
                @Html.DisplayNameFor(model => model.Country)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Country.Name)
            </dd>
        </dl>
    </div>
</div>

<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-info me-2">Edit</a>
    <a asp-action="Index" class="btn btn-secondary">Back</a>
</div>

BilheticaAeronauticaWeb/Views/Airports/Edit.cshtml
@model BilheticaAeronauticaWeb.Models.AirportViewModel

@{
    ViewData["Title"] = "Edit";
}
</br>
<h1>Edit</h1>

<hr />
<div class="row justify-content-center">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CountryId" class="control-label">Country</label>
                <select asp-for="CountryId" id="CountryId" asp-items="ViewBag.Countries" class="form-control">
                </select>
                <span asp-validation-for="CountryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CityId" class="control-label">City</label>
                <select asp-for="CityId" id="CityId" asp-items="ViewBag.Cities" class="form-control">
                    <option value="">Select a city</option>
                </select>
                <span asp-validation-for="CityId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-info me-2" />
                <a asp-action="Index" class="btn btn-danger btn-dark">Back</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");
}

<script type="text/javascript">
        $(document).ready(function () {
            function loadCities() {
                var countryId = $("#CountryId").val();
                if (countryId) {
                    $("#CityId").empty();
                    $.ajax({
                        url: '@Url.Action("GetCitiesAsync", "Airports")',
                        type: 'POST',
                        dataType: 'json',
                        data: { countryId: countryId },
                        success: function (cities) {
                            $("#CityId").append('<option value="0">(Select a city...)</option>');
                            $.each(cities, function (i, city) {
                                $("#CityId").append('<option value="' + city.id + '">' + city.name + '</option>');
                            });
                        },
                        error: function (ex) {
                            alert('Failed to retrieve cities.' + ex);
                        }
                    });
                } else {
                    // Optional: clear city dropdown if no country selected
                    $("#CityId").empty();
                    $("#CityId").append('<option value="0">(Select a city...)</option>');
                }
            }

            // Initial load for the pre-selected country on page load
            loadCities();

            // Load cities again whenever country changes
            $("#CountryId").change(function () {
                loadCities();
            });
        });
</script>

        }

BilheticaAeronauticaWeb/Views/Airports/Index.cshtml
@using Newtonsoft.Json
@using Syncfusion.EJ2.Maps;
@model IEnumerable<BilheticaAeronauticaWeb.Entities.Airport>


@{
    var propertyPath = new[] { "name" };


    var countryDataJson = ViewBag.countryData;
    var map = ViewBag.worldmap;
}

<br/>
<div class="card mb-4">
    <div class="card-header">
    </div>
    <div class="card-body">
        <table id="datatablesSimple" class="table table-bordered">
            <thead>
                <tr>
                    <th>
                        Airport
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.City.Name)
                    </th>
                    <th>
                        Country
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Country.ImageFullPath)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.City.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Country.Name)
                        </td>
                        <td>
                            @if (item.Country != null && !string.IsNullOrEmpty(item.Country.ImageFullPath))

                            {
                                <img src="@Url.Content(item.Country.ImageFullPath)" alt="Image" style="width:100px;height:150px;max-width:100%;height:auto;" />
                            }
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning btn-light">Edit</a>
                            <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-dark">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

<p>
            <a asp-action="Create" class="btn btn-info">Add airport</a>
</p>

@*         <div id="container" style="height:400px"></div> *@

        <ejs-maps id="maps">
            <e-maps-titlesettings text="Currently flying in these countries"></e-maps-titlesettings>
            <e-maps-layers>
                <e-maps-layer shapeData="@(map)"
                              shapeDataPath="Country"
                              shapePropertyPath="propertyPath"
                              dataSource='@countryDataJson'>
                    <e-layersettings-shapesettings colorValuePath="Color"
                                                   fill="#E5E5E5">
                    </e-layersettings-shapesettings>
                </e-maps-layer>
            </e-maps-layers>
        </ejs-maps>


@section Scripts {
    <script>
        $(document).ready(function () {
            $('#datatablesSimple').DataTable({
                pageLength: 10,
                language: {
            search: "Search airports: ",
            lengthMenu: "_MENU_" 
                }
            });
        });
    // </script>

            }